// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class AuthSysGroupSysSection
    {
        /// <summary>
        /// 流水號，起始值1，遞增值1
        /// </summary>
        public int AuthSysGroupSysSectionSN { get; set; }
        public int SysSectionSN { get; set; }
        public int SysGroupSN { get; set; }
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// 網站編號
        /// </summary>
        public string WebSiteID { get; set; }

    }
}