// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class AuthSysGroupWebLevel
    {
        /// <summary>
        /// 流水號，起始值1，遞增值1
        /// </summary>
        public int AuthSysGroupWebLevelSN { get; set; }
        /// <summary>
        /// 網站編號(當AuthType=Module時此欄位為空值)
        /// </summary>
        public string WebSiteID { get; set; }
        public int WebLevelSN { get; set; }
        public string Lang { get; set; }
        /// <summary>
        /// 權限類別，代碼如下Module：模組設定、Article：文章維護、Auth：權限設定
        /// </summary>
        public string AuthType { get; set; }
        public int SysGroupSN { get; set; }
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime? CreatedDate { get; set; }
    }
}