// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApplyPage
    {
        /// <summary>
        /// 序號
        /// </summary>
        public int CaseApplyPageSn { get; set; }
        /// <summary>
        /// 頁面類型 1-民意信箱前台頁面 2-郵件內容
        /// </summary>
        public string PageType { get; set; }
        /// <summary>
        /// 頁面名稱
        /// </summary>
        public string PageName { get; set; }
        /// <summary>
        /// 頁面標題
        /// </summary>
        public string PageTitle { get; set; }
        /// <summary>
        /// 頁面內容
        /// </summary>
        public string PageContent { get; set; }
        /// <summary>
        /// 是否啟用內容 否:0 是:1
        /// </summary>
        public bool ContentEnaled { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        public DateTime CreateDate { get; set; }
        /// <summary>
        /// 建立使用者
        /// </summary>
        public string CreateUser { get; set; }
        /// <summary>
        /// 修改時間
        /// </summary>
        public DateTime ProcessDate { get; set; }
        /// <summary>
        /// 修改使用者
        /// </summary>
        public string ProcessUser { get; set; }
        /// <summary>
        /// 排序編號
        /// </summary>
        public int SortOrder { get; set; }
    }
}