// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApplyClassTo
    {
        public int CaseApplyClassToSN { get; set; }
        /// <summary>
        /// 對應 意見分類 SN
        /// </summary>
        public int? CaseApplyClassSN { get; set; }
        /// <summary>
        /// 意見分類 負責人 部門SN
        /// </summary>
        public int? SysDepartmentSN { get; set; }
        /// <summary>
        /// 意見分類 負責人 姓名
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 意見分類 負責人 email
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 是否啟用：1 啟用、0 停用
        /// </summary>
        public string IsEnable { get; set; }
        public string CreatedUserID { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ProcessUserID { get; set; }
        public DateTime ProcessDate { get; set; }
        public string ProcessIPAddress { get; set; }
    }
}