// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApplyPageExtend
    {
        /// <summary>
        /// 序號
        /// </summary>
        public int CaseApplyPageExtendSn { get; set; }
        /// <summary>
        /// 頁面序號
        /// </summary>
        public int CaseApplyPageSn { get; set; }
        /// <summary>
        /// 擴充內容
        /// </summary>
        public string ExtendContent { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        public DateTime CreateDate { get; set; }
        /// <summary>
        /// 建立使用者
        /// </summary>
        public string CreateUser { get; set; }
        /// <summary>
        /// 修改時間
        /// </summary>
        public DateTime ProcessDate { get; set; }
        /// <summary>
        /// 修改使用者
        /// </summary>
        public string ProcessUser { get; set; }
        /// <summary>
        /// 排序編號
        /// </summary>
        public int SortOrder { get; set; }
    }
}