// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApplySpeedApiLog
    {
        public int SpeedApiLogSn { get; set; }
        public int CaseApplySn { get; set; }
        /// <summary>
        /// UploadAttachment、AddNewCase、SearchCase、DownloadAttachment
        /// </summary>
        public string Action { get; set; }
        /// <summary>
        /// 請求回應
        /// </summary>
        public string StatusCode { get; set; }
        /// <summary>
        /// 傳送資料
        /// </summary>
        public string Request { get; set; }
        /// <summary>
        /// 回應訊息 200時為空字串
        /// </summary>
        public string Message { get; set; }
        /// <summary>
        /// 1 : OK 2 : Fail 3 : Error
        /// </summary>
        public string ApiStatus { get; set; }
        /// <summary>
        /// 回傳訊息，OK時回傳空字串
        /// </summary>
        public string ApiMessage { get; set; }
        /// <summary>
        /// 民意信箱 : MailBox 、排程 : Console 、後台UserID
        /// </summary>
        public string CreatedUserId { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}