// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApplyValidate
    {
        /// <summary>
        /// 驗證信箱　流水碼
        /// </summary>
        public int CaseValidateSN { get; set; }
        /// <summary>
        /// 申請信箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 驗證key
        /// </summary>
        public string Token { get; set; }
        /// <summary>
        /// 驗證有效時間
        /// </summary>
        public DateTime EffectiveDate { get; set; }
        /// <summary>
        /// 驗證有??
        /// </summary>
        public DateTime? StatementCheckDate { get; set; }
        /// <summary>
        /// 驗證狀態 0 : 新增 1 : 已驗證
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// 用途 ?
        /// </summary>
        public string BowserInfo { get; set; }
        /// <summary>
        /// 使用者IP
        /// </summary>
        public string ProcessIPAddress { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        public DateTime CreateDate { get; set; }
        /// <summary>
        /// 修改時間
        /// </summary>
        public DateTime ProcessDate { get; set; }
    }
}