// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApplyClass
    {
        /// <summary>
        /// 流水碼
        /// </summary>
        public int CaseApplyClassSN { get; set; }
        /// <summary>
        /// 網站編號
        /// </summary>
        public string WebSiteID { get; set; }
        /// <summary>
        /// 預設之後有多層的情況
        /// </summary>
        public int? ParentSN { get; set; }
        /// <summary>
        /// 意見分類
        /// </summary>
        public string CaseName { get; set; }
        /// <summary>
        /// 意見分類(英文)
        /// </summary>
        public string CaseNameEN { get; set; }
        /// <summary>
        /// 部門流水碼
        /// </summary>
        public int? SysDepartmentSN { get; set; }
        /// <summary>
        /// 意見分類代號
        /// </summary>
        public string CaseNo { get; set; }
        /// <summary>
        /// 公文子分類
        /// </summary>
        public string CaseType { get; set; }
        /// <summary>
        /// 辦理天數
        /// </summary>
        public int? HandleDate { get; set; }
        /// <summary>
        /// 備註200個字
        /// </summary>
        public string info { get; set; }
        /// <summary>
        /// 是否啟用：1 啟用、0 停用
        /// </summary>
        public string IsEnable { get; set; }
        public string ProcessUserID { get; set; }
        public DateTime ProcessDate { get; set; }
        public string ProcessIPAddress { get; set; }
        public string CreatedUserID { get; set; }
        public DateTime CreatedDate { get; set; }
        public int SortOrder { get; set; }

        /// <summary>
        /// 大分類
        /// </summary>
        public string SysCategoryKey { get; set; }

    }
}