// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApplyWeb
    {
        /// <summary>
        /// 識別碼
        /// </summary>
        public int CaseApplyWebSN { get; set; }
        /// <summary>
        /// 站台編號
        /// </summary>
        public string WebSiteID { get; set; }
        /// <summary>
        /// 標題
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// SEODescription
        /// </summary>
        public string SEODescription { get; set; }
        /// <summary>
        /// SEOKeywords
        /// </summary>
        public string SEOKeywords { get; set; }
        /// <summary>
        /// GACode
        /// </summary>
        public string GACode { get; set; }
        /// <summary>
        /// 滿意度開關
        /// </summary>
        public bool Satisfaction { get; set; }
        /// <summary>
        /// 頁尾設定
        /// </summary>
        public string Footer { get; set; }
        /// <summary>
        /// 啟用與否
        /// </summary>
        public string IsEnable { get; set; }
        /// <summary>
        /// 建立者
        /// </summary>
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 編輯者
        /// </summary>
        public string ProcessUserID { get; set; }
        /// <summary>
        /// 編輯時間
        /// </summary>
        public DateTime ProcessDate { get; set; }
        /// <summary>
        /// 編輯者IP
        /// </summary>
        public string ProcessIPAddress { get; set; }
    }
}