// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApply
    {
        /// <summary>
        /// 流水碼
        /// </summary>
        public int CaseApplySN { get; set; }
        /// <summary>
        /// 對應驗證信 流水碼
        /// </summary>
        public int CaseValidateSN { get; set; }
        /// <summary>
        /// 標題
        /// </summary>
        public string Subject { get; set; }
        /// <summary>
        /// 內文
        /// </summary>
        public string CaseContent { get; set; }
        /// <summary>
        /// 意見分類SN
        /// </summary>
        public int CaseApplyClassSN { get; set; }
        /// <summary>
        /// 意見分類 備用
        /// </summary>
        public string CaseCategoryL2 { get; set; }
        /// <summary>
        /// 申請者姓名
        /// </summary>
        public string ApplyUser { get; set; }
        /// <summary>
        /// 申請者信箱
        /// </summary>
        public string ContactEmail { get; set; }
        /// <summary>
        /// 區域號碼
        /// </summary>
        public string TelAreacode { get; set; }
        /// <summary>
        /// 家裡電話
        /// </summary>
        public string Tel { get; set; }
        /// <summary>
        /// 分機號碼
        /// </summary>
        public string TelExtension { get; set; }
        /// <summary>
        /// 手機號碼
        /// </summary>
        public string Mobile { get; set; }
        /// <summary>
        /// 案件編號- yyyyMMDDhhZZZZ (ZZZZ為流水碼)每小時最大可以受理9999
        /// </summary>
        public string CaseNo { get; set; }
        /// <summary>
        /// 案件驗證碼 隨機碼
        /// </summary>
        public string CasePwd { get; set; }
        /// <summary>
        /// 案件 接收驗證信 有效期限
        /// </summary>
        public DateTime? EffectiveDate { get; set; }
        /// <summary>
        /// 使用者 確認 案件成立時間
        /// </summary>
        public DateTime? AcceptDate { get; set; }
        /// <summary>
        /// 最後重寄確認信時間
        /// </summary>
        public DateTime? ResendDate { get; set; }
        /// <summary>
        /// 重寄次數
        /// </summary>
        public int? ResendNum { get; set; }
        /// <summary>
        /// 公文回覆內文
        /// </summary>
        public string ReplyContent { get; set; }
        /// <summary>
        /// 對方回傳的
        /// </summary>
        public string ReplyCaseNo { get; set; }
        public string ReplyCasePwd { get; set; }
        /// <summary>
        /// 回覆狀態 :  0 尚未回覆  1 公文系統 2 管理系統回覆
        /// </summary>
        public string ReplySource { get; set; }
        /// <summary>
        /// 對方回傳的回覆時間
        /// </summary>
        public DateTime? ReplyDate { get; set; }
        /// <summary>
        /// 接收資料的時間
        /// </summary>
        public DateTime? ReplyApiDate { get; set; }
        /// <summary>
        /// 系統回復的訊息
        /// </summary>
        public string ReplySource2 { get; set; }
        /// <summary>
        /// 系統回復的訊息的時間
        /// </summary>
        public DateTime? ReplySource2Date { get; set; }
        /// <summary>
        /// 0-&gt;案件成立 1 寄送確認信 2 寄送確認信失敗  3 完成確認信 4 寄送受理信成功   5 寄送受理信失敗 9 結案
        /// </summary>
        public string Status { get; set; }
        public DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public DateTime ProcessDate { get; set; }
        public string ProcessUser { get; set; }
        public string ProcessIPAddress { get; set; }
        public string WebSiteId { get; set; }
        /// <summary>
        /// 公文機關
        /// </summary>
        public string DocDept { get; set; }
        /// <summary>
        /// 公文文號
        /// </summary>
        public string DocNo { get; set; }
        /// <summary>
        /// 原始分類代碼
        /// </summary>
        public int? OriginalCaseApplyClassSn { get; set; }
        /// <summary>
        /// 原始分類機關代碼
        /// </summary>
        public int? OriginalClassDeptSn { get; set; }
    }
}