// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class CaseApplySurvey
    {
        public int CaseApplySurveySn { get; set; }
        public int? CaseApplySn { get; set; }
        /// <summary>
        /// 滿意度1~10分
        /// </summary>
        public int CaseSatisfy { get; set; }
        /// <summary>
        /// A:完全解決 B:部份解決 C:沒有解決 D:提出建議
        /// </summary>
        public string CaseSolved { get; set; }
        /// <summary>
        /// A:無 B:未解決 C:態度不佳 D: 時間太慢 E:欠缺誠意 F:引用錯誤 G:推諉責任 H:與實情不符
        /// </summary>
        public string CaseDefect { get; set; }
        /// <summary>
        /// 建議事項
        /// </summary>
        public string CaseProposal { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime? CreateDate { get; set; }
    }
}