// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class RelSysUserGroup
    {
        /// <summary>
        /// 流水號，起始值1，遞增值1
        /// </summary>
        public int RelSysGroupUserSN { get; set; }
        /// <summary>
        /// 使用者帳號
        /// </summary>
        public string UserID { get; set; }
        /// <summary>
        /// 群組流水號
        /// </summary>
        public int? SysGroupSN { get; set; }
        public string CreatedIPAddress { get; set; }
        /// <summary>
        /// 建檔日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        public string CreatedUserID { get; set; }
        public int SortOrder { get; set; }
    }
}