// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class RelWebFileContent
    {
        /// <summary>
        /// 流水號，起始值1，遞增值1
        /// </summary>
        public int RelWebFileContentSN { get; set; }
        public int WEBFileSN { get; set; }
        /// <summary>
        /// 資料來源：WEBNEWS、WEBBanner、WebJournal
        /// </summary>
        public string SourceTable { get; set; }
        public int SourceSN { get; set; }
        /// <summary>
        /// 分辨群組檔案
        /// </summary>
        public string GroupID { get; set; }
        public int? PageView { get; set; }
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortOrder { get; set; }
    }
}