// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class SysBlocklist
    {
        /// <summary>
        /// 流水號，起始值1，遞增值1
        /// </summary>
        public int SysBlocklistSN { get; set; }
        /// <summary>
        /// M 後台、W 前台
        /// </summary>
        public string WebType { get; set; }
        /// <summary>
        /// 0 不設、1 黑名單、2 白名單
        /// </summary>
        public string BlockType { get; set; }
        /// <summary>
        /// 被阻擋的IP
        /// </summary>
        public string BlockedIPAddress { get; set; }
        /// <summary>
        /// 是否啟用：1 啟用、0 停用、-99 刪除
        /// </summary>
        public string IsEnable { get; set; }
        /// <summary>
        /// 處理人員
        /// </summary>
        public string ProcessUserID { get; set; }
        /// <summary>
        /// 處理時間
        /// </summary>
        public DateTime? ProcessDate { get; set; }
        /// <summary>
        /// 處理人員IP
        /// </summary>
        public string ProcessIPAddress { get; set; }
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime? CreatedDate { get; set; }
    }
}