// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class SysCategory
    {
        public int SysCategorySN { get; set; }
        /// <summary>
        /// 參數代碼
        /// </summary>
        public string SysCategoryKey { get; set; }
        public string ParentKey { get; set; }
        public string WebSiteID { get; set; }
        public string Lang { get; set; }
        /// <summary>
        /// 參數值
        /// </summary>
        public string Value { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 處理人員
        /// </summary>
        public string ProcessUserID { get; set; }
        /// <summary>
        /// 處理時間
        /// </summary>
        public DateTime? ProcessDate { get; set; }
        /// <summary>
        /// 處理人員IP
        /// </summary>
        public string ProcessIPAddress { get; set; }
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime? CreatedDate { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortOrder { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string IsEnable { get; set; }

        /// <summary>
        /// 主Key
        /// </summary>
        public int MainSN { get; set; }

    }
}