// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class SysDepartment
    {
        /// <summary>
        /// 流水號，起始值1，遞增值1
        /// </summary>
        public int SysDepartmentSN { get; set; }
        /// <summary>
        /// 單位編號
        /// </summary>
        public string DepartmentID { get; set; }
        /// <summary>
        /// 父單位流水號
        /// </summary>
        public int? ParentID { get; set; }
        /// <summary>
        /// 部門名稱
        /// </summary>
        public string DepartmentName { get; set; }
        /// <summary>
        /// 部門簡稱
        /// </summary>
        public string ShortName { get; set; }
        /// <summary>
        /// 部門描述
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 是否啟用：1 啟用、0 停用
        /// </summary>
        public string IsEnable { get; set; }
        public string ProcessUserID { get; set; }
        /// <summary>
        /// 最後異動日期
        /// </summary>
        public DateTime ProcessDate { get; set; }
        public string ProcessIPAddress { get; set; }
        /// <summary>
        /// 最後異動日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        public string CreatedUserID { get; set; }
        public int SortOrder { get; set; }

        /// <summary>
        /// 語系
        /// </summary>
        public string Lang { get; set; }
        /// <summary>
        /// 主Key
        /// </summary>
        public int? MainSN { get; set; }

        /// <summary>
        /// 網站編號
        /// </summary>
        public string WebSiteId { get; set; }
    }
}