// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DBModel
{
    public partial class SysPwdHistory
    {
        /// <summary>
        /// 流水碼
        /// </summary>
        public int SysPwdHistorySN { get; set; }
        /// <summary>
        /// 使用者帳號
        /// </summary>
        public string UserID { get; set; }
        /// <summary>
        /// 加密後儲存
        /// </summary>
        [Column("Password")]
        public string p_w_d { get; set; }
        public string CreateUserID { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}