// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DBModel
{
    /// <summary>
    /// 使用者
    /// </summary>
    public partial class SysUser
    {
        public int SysUserSN { get; set; }

        /// <summary>
        /// AD帳號
        /// </summary>
        public string ADUserID { get; set; }
        /// <summary>
        /// 帳號
        /// </summary>
        public string UserID { get; set; }
        /// <summary>
        /// 使用者名稱
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 英文名稱
        /// </summary>
        public string EngName { get; set; }
        /// <summary>
        /// 暱稱
        /// </summary>
        public string NickName { get; set; }
        /// <summary>
        /// 性別：F，M
        /// </summary>
        public string Gender { get; set; }
        /// <summary>
        /// 密碼 加密後儲存
        /// </summary>
        [Column("Password")]
        public string p_w_d { get; set; }
        /// <summary>
        /// 使用者狀態：0 停用，1 啟用 -99 刪除
        /// </summary>
        public string UserSatus { get; set; }
        /// <summary>
        /// 連絡電話
        /// </summary>
        public string Tel { get; set; }
        /// <summary>
        /// 連絡電話
        /// </summary>
        public string Mobile { get; set; }
        /// <summary>
        /// 聯絡信箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 停用日期
        /// </summary>
        public DateTime? DisableDate { get; set; }
        /// <summary>
        /// 最後登入日期
        /// </summary>
        public DateTime? LastLoginDate { get; set; }
        /// <summary>
        /// 最後修改密碼日期
        /// </summary>
        public DateTime? PwdLastUpdate { get; set; }
        /// <summary>
        /// 登入失敗次數
        /// </summary>
        public int? ErrLoginnum { get; set; }
        /// <summary>
        /// 員工編號
        /// </summary>
        public string EmpID { get; set; }
        /// <summary>
        /// 職稱
        /// </summary>
        public string JobTitle { get; set; }
        /// <summary>
        /// 辦公室電話
        /// </summary>
        public string OfficePhone { get; set; }
        /// <summary>
        /// 照片
        /// </summary>
        public string Photo { get; set; }
        /// <summary>
        /// 部門編號
        /// </summary>
        public string DepartmentID { get; set; }
        /// <summary>
        /// 處理人員
        /// </summary>
        public string ProcessUserID { get; set; }
        /// <summary>
        /// 處理時間
        /// </summary>
        public DateTime? ProcessDate { get; set; }
        /// <summary>
        /// 處理人員IP
        /// </summary>
        public string ProcessIPAddress { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime? DateCreated { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortOrder { get; set; }
    }
}