// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class SysZipCode
    {
        /// <summary>
        /// 縣市區域代碼表-流水碼
        /// </summary>
        public int ZipCodeSn { get; set; }
        /// <summary>
        /// 名稱
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 父層SN
        /// </summary>
        public int? ParentSn { get; set; }
        /// <summary>
        /// 代碼
        /// </summary>
        public string ZipCode { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortOrder { get; set; }
        /// <summary>
        /// 是否啟用：1 啟用、0 停用     -99刪除
        /// </summary>
        public string IsEnable { get; set; }
    }
}