// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class vw_AllLink
    {
        public string Path { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
    }
}