// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class vw_SysSection
    {
        public int SysSectionSN { get; set; }
        public int? ParentSN { get; set; }
        public string ActionPath { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public string IsEnableC { get; set; }
        public int? SortOrderC { get; set; }
        public int? ParentSNP { get; set; }
        public string ActionPathP { get; set; }
        public string TitleP { get; set; }
        public string IconP { get; set; }
        public string IsEnableP { get; set; }
        public int? SortOrderP { get; set; }
    }
}