// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class vw_test
    {
        public int Id { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}