// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class vw_UserLeftDep
    {
        public long? ROWID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string EngName { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public string Password { get; set; }
        public string UserSatus { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public DateTime? DisableDate { get; set; }
        public DateTime? LastLoginDate { get; set; }
        public DateTime? PwdLastUpdate { get; set; }
        public int? ErrLoginnum { get; set; }
        public string EmpID { get; set; }
        public string JobTitle { get; set; }
        public string OfficePhone { get; set; }
        public string Photo { get; set; }
        public string DepartmentID { get; set; }
        public string ProcessUserID { get; set; }
        public DateTime? ProcessDate { get; set; }
        public string ProcessIPAddress { get; set; }
        public DateTime? DateCreated { get; set; }
        public int? SortOrder { get; set; }
        public int? SysDepartmentSN { get; set; }
        public string Expr1 { get; set; }
        public int? ParentID { get; set; }
        public string DepartmentName { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string IsEnable { get; set; }
        public string Expr2 { get; set; }
        public DateTime? Expr3 { get; set; }
        public string Expr4 { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedUserID { get; set; }
        public int? Expr5 { get; set; }
    }
}