// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class vw_WebLevel
    {
        public int WebLevelDSN { get; set; }
        public int WebLevelMSN { get; set; }
        public int ParentSN { get; set; }
        public string WebSiteID { get; set; }
        public string Lang { get; set; }
        public int HierarchyID { get; set; }
        public string WeblevelType { get; set; }
        public string Module { get; set; }
        public string ParameterM { get; set; }
        public string Title { get; set; }
        public string FatFooterShow { get; set; }
        public string MainMenuShow { get; set; }
        public string SubMemuShow { get; set; }
        public string RSSShow { get; set; }
        public int? PageView { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string ParameterD { get; set; }
        public string IsEnable { get; set; }
        public string ProcessUserID { get; set; }
        public DateTime ProcessDate { get; set; }
        public string ProcessIPAddress { get; set; }
        public string CreatedUserID { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}