// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WebCntLink
    {
        /// <summary>
        /// 資料來源：WEBNEWS、WEBLEVELD
        /// </summary>
        public string SourceTable { get; set; }
        public int SourceSN { get; set; }
        /// <summary>
        /// 解析CKEditor裡的連結
        /// </summary>
        public string URL { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}