// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WebFileDownLoads
    {
        /// <summary>
        /// 流水號，起始值1，遞增值1
        /// </summary>
        public int FileSN { get; set; }
        public int RelWebFileContentSN { get; set; }
        public int WEBFileSN { get; set; }
        /// <summary>
        /// 下載數
        /// </summary>
        public int DownLoads { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
    }
}