// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WebHrefSource
    {
        /// <summary>
        /// 流水碼
        /// </summary>
        public int Sn { get; set; }
        /// <summary>
        /// 父層SN
        /// </summary>
        public int? ParentSn { get; set; }
        /// <summary>
        /// 來源table
        /// </summary>
        public string Source { get; set; }
        /// <summary>
        /// 網站編號
        /// </summary>
        public string WebSiteID { get; set; }

        /// <summary>
        /// 來源SN
        /// </summary>
        public int? SourceSn { get; set; }
        /// <summary>
        /// 來源父層SN
        /// </summary>
        public int? SourceSnparent { get; set; }
        /// <summary>
        /// 連結
        /// </summary>
        public string Href { get; set; }
        /// <summary>
        /// 起始時間
        /// </summary>
        public DateTime? StardDate { get; set; }
        /// <summary>
        /// 結束時間
        /// </summary>
        public DateTime? EndDate { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public int? IsEnable { get; set; }
        /// <summary>
        /// 異動時間
        /// </summary>
        public DateTime? ProcessDate { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Info { get; set; }
    }
}