// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WebLink
    {
        public int WebLinkSN { get; set; }
        /// <summary>
        /// 網站編號
        /// </summary>
        public string WebSiteID { get; set; }
        /// <summary>
        /// 語言：TW、EN
        /// </summary>
        public string Lang { get; set; }
        /// <summary>
        /// 期刊標題e.g.第三十七卷第二期
        /// </summary>
        public string Title { get; set; }
        public string URL { get; set; }
        /// <summary>
        /// 資料來源：WEBNEWS，參考Utility.SysConst.SourceTable
        /// </summary>
        public string SourceTable { get; set; }
        /// <summary>
        /// WEBNEWS流水號
        /// </summary>
        public int SourceSN { get; set; }
        /// <summary>
        /// 分辨相關連結群組(目前係通僅1組，為防止以後會有多個相關連結區)
        /// </summary>
        public string GroupID { get; set; }
        /// <summary>
        /// 瀏覽/點閱數
        /// </summary>
        public int? PageView { get; set; }
        /// <summary>
        /// 是否發布：0 不公開，1 發布、2草稿
        /// </summary>
        public string IsEnable { get; set; }
        /// <summary>
        /// 上架日期時間
        /// </summary>
        public DateTime? StartDate { get; set; }
        /// <summary>
        /// 上架日期時間
        /// </summary>
        public DateTime? EndDate { get; set; }
        /// <summary>
        /// 處理人員
        /// </summary>
        public string ProcessUserID { get; set; }
        /// <summary>
        /// 處理時間
        /// </summary>
        public DateTime? ProcessDate { get; set; }
        /// <summary>
        /// 處理人員IP
        /// </summary>
        public string ProcessIPAddress { get; set; }
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime? CreatedDate { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortOrder { get; set; }
    }
}