// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WebLevelSortLog
    {
        /// <summary>
        /// 流水碼
        /// </summary>
        public int WebLevelSortLogSN { get; set; }
        /// <summary>
        /// 網站編號
        /// </summary>
        public string WebSiteID { get; set; }
        /// <summary>
        /// 語系
        /// </summary>
        public string Lang { get; set; }
        /// <summary>
        /// 父節點代號
        /// </summary>
        public int WebLevelParentSN { get; set; }
        /// <summary>
        /// 建立者
        /// </summary>
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立時間
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 排序方式:0 系統排序、1最新日期排序
        /// </summary>
        public string BeforeSortType { get; set; }
        /// <summary>
        /// 排序方式:0 系統排序、1最新日期排序
        /// </summary>
        public string AfterSortType { get; set; }
        /// <summary>
        /// 0:更改為系統排序、1:更改為最新日期排序、2:調整資料排序位置
        /// </summary>
        public string SortMethod { get; set; }
    }
}