// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WEBNews
    {
        /// <summary>
        /// 流水號，起始值1，遞增值1
        /// </summary>
        public int WEBNewsSN { get; set; }
        /// <summary>
        /// 網站編號
        /// </summary>
        public string WebSiteID { get; set; }
        /// <summary>
        /// 單元序號[WebLevel]
        /// </summary>
        public int WebLevelSN { get; set; }
        /// <summary>
        /// 語言：TW、EN
        /// </summary>
        public string Lang { get; set; }
        /// <summary>
        /// 單元模組，代碼如下CP:單頁、NEWS：條列式(一般模組)、LINK： 相關連結、Footer：頁尾內容
        /// </summary>
        public string Module { get; set; }
        /// <summary>
        /// 文章模式，0：圖文、1：附件、2：連結、3:YoutubeID、4:iframe
        /// </summary>
        public string ArticleType { get; set; }
        /// <summary>
        /// 主標題
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 子標題
        /// </summary>
        public string SubTitle { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 公布日期
        /// </summary>
        public DateTime? PublishDate { get; set; }
        /// <summary>
        /// 內容
        /// </summary>
        public string ContentText { get; set; }
        /// <summary>
        /// 相關連結
        /// </summary>
        public string URL { get; set; }
        /// <summary>
        /// 另開視窗_blank、_Self
        /// </summary>
        public string target { get; set; }
        public string YoutubeID { get; set; }
        /// <summary>
        /// 是否置頂：1 是、0 否
        /// </summary>
        public string IsTop { get; set; }
        public string DepartmentID { get; set; }
        /// <summary>
        /// 瀏覽/點閱數
        /// </summary>
        public int? PageView { get; set; }
        /// <summary>
        /// 上架時間
        /// </summary>
        public DateTime? StartDate { get; set; }
        /// <summary>
        /// 下架時間
        /// </summary>
        public DateTime? EndDate { get; set; }
        /// <summary>
        /// 是否啟用：1 啟用、0 停用     -99刪除
        /// </summary>
        public string IsEnable { get; set; }
        /// <summary>
        /// 處理人員
        /// </summary>
        public string ProcessUserID { get; set; }
        /// <summary>
        /// 處理時間
        /// </summary>
        public DateTime ProcessDate { get; set; }
        /// <summary>
        /// 處理人員IP
        /// </summary>
        public string ProcessIPAddress { get; set; }
        public string CreatedUserID { get; set; }
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortOrder { get; set; }
        /// <summary>
        /// 主Key
        /// </summary>
        public int? MainSN { get; set; }
        /// <summary>
        /// 版面呈現
        /// </summary>
        public string PageViewType { get; set; }
        /// <summary>
        /// 主題標籤(會再拉出一張表紀錄-WEBNewsExtend會調整)
        /// </summary>
        public string Tag { get; set; }
        /// <summary>
        /// 自定標籤
        /// </summary>
        public int? CustomizeTagSn { get; set; }
        /// <summary>
        /// 首長行程縣市
        /// </summary>
        public int? ZipCodeSn { get; set; }
        /// <summary>
        /// 關鍵字
        /// </summary>
        public string KeyWord { get; set; }
        /// <summary>
        /// 整體績效
        /// </summary>
        public int? Performance { get; set; }
        /// <summary>
        /// 政策計畫
        /// </summary>
        public int? EProject { get; set; }
        /// <summary>
        /// 服務對象(會再拉出一張表紀錄-WEBNewsExtend會調整)
        /// </summary>
        public string ServiceObject { get; set; }
        /// <summary>
        /// 其他語系連結
        /// </summary>
        public string OtherLangerUrl { get; set; }
        /// <summary>
        /// 靜態化網址
        /// </summary>
        public string StatesUrl { get; set; }

        /// <summary>
        /// SEODescription
        /// </summary>
        public string SEODescription { get; set; }
        /// <summary>
        /// SEOKeywords
        /// </summary>
        public string SEOKeywords { get; set; }
    }
}