// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WebNewsSchedule
    {
        /// <summary>
        /// 行程關聯表-流水碼
        /// </summary>
        public int WebNewsScheduleSn { get; set; }
        /// <summary>
        /// 來源 : webNews (Module 是 Schedule)
        /// </summary>
        public int? ToWebNewsSn { get; set; }
        /// <summary>
        /// 關聯-哪些新聞
        /// </summary>
        public int? FromWebNewsSn { get; set; }
    }
}