// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WEBNewsExtend
    {
        /// <summary>
        /// 本身流水碼
        /// </summary>
        public int WEBNewsExtendSN { get; set; }
        /// <summary>
        /// WEBNewsSN
        /// </summary>
        public int? WEBNewsSN { get; set; }
        /// <summary>
        /// SysCategoryKey
        /// </summary>
        public string SysCategoryKey { get; set; }
        /// <summary>
        /// GroupID
        /// </summary>
        public string GroupID { get; set; }
        /// <summary>
        /// 擴充1
        /// </summary>
        public string Column_1 { get; set; }
        /// <summary>
        /// 擴充2
        /// </summary>
        public string Column_2 { get; set; }
        /// <summary>
        /// 擴充3
        /// </summary>
        public int? Column_3 { get; set; }
    }
}