// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WEBOpenDataDetail
    {
        /// <summary>
        /// 流水號
        /// </summary>
        public int OpenDataDetailSN { get; set; }
        /// <summary>
        /// 外來鍵
        /// </summary>
        public int OpenDataMainSN { get; set; }
        /// <summary>
        /// 關聯：0.innerjoin、1.leftjoin、2.rightjoin
        /// </summary>
        public int? Join { get; set; }
        /// <summary>
        /// 代號
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// SQL條件
        /// </summary>
        public string SQLParameter { get; set; }
        /// <summary>
        /// 資料庫名稱
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// 開始時間
        /// </summary>
        public DateTime? ProcessDate { get; set; }
        /// <summary>
        /// 結束時間
        /// </summary>
        public DateTime? DateCreated { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortOrder { get; set; }
    }
}