// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WEBOpenDataSchema
    {
        /// <summary>
        /// 流水號
        /// </summary>
        public int OpenDataSchemaSN { get; set; }
        /// <summary>
        /// 外來鍵
        /// </summary>
        public int OpenDataMainSN { get; set; }
        /// <summary>
        /// 外來鍵
        /// </summary>
        public int OpenDataDetailSN { get; set; }
        /// <summary>
        /// 資料庫名稱
        /// </summary>
        public string TableName { get; set; }
        /// <summary>
        /// 是否必輸
        /// </summary>
        public string isRequired { get; set; }
        /// <summary>
        /// 欄位
        /// </summary>
        public string Column { get; set; }
        /// <summary>
        /// 欄位名稱
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 資料型別
        /// </summary>
        public string DataType { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? SortOrder { get; set; }
    }
}