// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBModel
{
    public partial class WebSiteExtend
    {
        /// <summary>
        /// 流水碼
        /// </summary>
        public int WebSiteExtendSN { get; set; }
        /// <summary>
        /// 網站編號
        /// </summary>
        public string WebSiteID { get; set; }
        /// <summary>
        /// 連結網址
        /// </summary>
        public string Url { get; set; }
        /// <summary>
        /// 標題
        /// </summary>
        public string Title { get; set; }
        public string Class { get; set; }
        /// <summary>
        /// 是否啟用：1 啟用、0 停用     -99刪除
        /// </summary>
        public string IsEnable { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int? Sort { get; set; }
    }
}